name: "running unit test, build docker image"
on:
  push:
    branches: [ main ]
    
jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-latest
    
    steps:
      - uses: action/chechout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: running test
        run: go test ./... -cover

