name: "running unit test, build docker image"
on:
  push:
    branches: [ main ]
    
jobs:
  unit-test:
    name: "unit test"
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: running test
        run: go test ./... -cover
  build-push-docker:
    name: "build images and push docker to docker registry"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -f Dockerfile -t dwiwidianto/kampus_merdeka:$(date +%s)
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME_REGISTRY}}
          password: ${{ DOCKER_TOKEN_REGISTRY }}
      - name: Push Image to Docker Registry
        run: docker push dwiwidianto/kampus_merdeka:latest
